# Generated by Django 4.1.2 on 2022-11-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arithmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('add', 'addition'), ('sub', 'subtraction'), ('mul', 'multiplication')], max_length=50)),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
            ],
        ),
    ]
