# Generated by Django 4.1.2 on 2022-11-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arithmetic',
            name='operation_type',
            field=models.CharField(choices=[('addition', 'addition'), ('subtraction', 'subtraction'), ('multiplication', 'multiplication')], max_length=50),
        ),
    ]
